apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-app
  namespace: argocd
spec:
  project: my-app-project
  source:
    repoURL: https://github.com/AravindS301/argocd-demo-practice/tree/main/practice-set-2.git
    targetRevision: HEAD
    path: manifest
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated: {}
